Document: libcvautomation
Title: Debian libcvautomation Manual
Author: <insert document author here>
Abstract: This manual describes what libcvautomation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcvautomation/libcvautomation.sgml.gz

Format: postscript
Files: /usr/share/doc/libcvautomation/libcvautomation.ps.gz

Format: text
Files: /usr/share/doc/libcvautomation/libcvautomation.text.gz

Format: HTML
Index: /usr/share/doc/libcvautomation/html/index.html
Files: /usr/share/doc/libcvautomation/html/*.html
