%module libcvautomation
%{
#include <libcvautomation/libcvautomation.h>
#include <libcvautomation/libcvautomation-opencv.h>
#include <libcvautomation/libcvautomation-xlib.h>
#include <libcvautomation/libcvautomation-xtest.h>
%}

%include <libcvautomation/libcvautomation.h>
%include <libcvautomation/libcvautomation-opencv.h>
%include <libcvautomation/libcvautomation-xlib.h>
%include <libcvautomation/libcvautomation-xtest.h>
