.TH "cvaPoint" 3 "13 Aug 2012" "Version 1.5" "libcvautomation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cvaPoint \- Very simple structure to standardize how points are used in libcvautomation.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libcvautomation.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Very simple structure to standardize how points are used in libcvautomation. 

\fBParameters:\fP
.RS 4
\fIx\fP An X-coordinate 
.br
\fIy\fP A Y-coordinate 
.RE
.PP

.PP
Definition at line 41 of file libcvautomation.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcvautomation from the source code.
